//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 04. 25. 12:54:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using ImageInsight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ImageInsight.Data
{

    public partial class ImageInsightDbContext : DbContext
    {

        public ImageInsightDbContext() :
            base()
        {
            OnCreated();
        }

        public ImageInsightDbContext(DbContextOptions<ImageInsightDbContext> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(@"Data Source=PROTO\SQLEXPRESS;Initial Catalog=ImageInsight;Integrated Security=True;Persist Security Info=True;TrustServerCertificate=True;");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Image> Images
        {
            get;
            set;
        }

        public virtual DbSet<TagFeedback> TagFeedbacks
        {
            get;
            set;
        }

        public virtual DbSet<User> Users
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.ImageMapping(modelBuilder);
            this.CustomizeImageMapping(modelBuilder);

            this.TagFeedbackMapping(modelBuilder);
            this.CustomizeTagFeedbackMapping(modelBuilder);

            this.UserMapping(modelBuilder);
            this.CustomizeUserMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Image Mapping

        private void ImageMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Image>().ToTable(@"Images", @"dbo");
            modelBuilder.Entity<Image>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Image>().Property(x => x.ImageUrl).HasColumnName(@"ImageUrl").HasColumnType(@"nvarchar(max)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType(@"nvarchar(255)").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Image>().Property(x => x.SourceUrl).HasColumnName(@"SourceUrl").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.SourceType).HasColumnName(@"SourceType").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Image>().Property(x => x.FlorenceCaption).HasColumnName(@"FlorenceCaption").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.RamTagsJson).HasColumnName(@"RamTagsJson").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.LlmTagsJson).HasColumnName(@"LlmTagsJson").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.FinalTagsJson).HasColumnName(@"FinalTagsJson").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.ValidationMode).HasColumnName(@"ValidationMode").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"'manual'");
            modelBuilder.Entity<Image>().Property(x => x.Status).HasColumnName(@"Status").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"'pending'");
            modelBuilder.Entity<Image>().Property(x => x.IsValidated).HasColumnName(@"IsValidated").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Image>().Property(x => x.ValidationDate).HasColumnName(@"ValidationDate").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<Image>().Property(x => x.ValidatedByUserId).HasColumnName(@"ValidatedByUserId").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Image>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime2").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<Image>().HasKey(@"Id");
        }

        partial void CustomizeImageMapping(ModelBuilder modelBuilder);

        #endregion

        #region TagFeedback Mapping

        private void TagFeedbackMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TagFeedback>().ToTable(@"TagFeedback", @"dbo");
            modelBuilder.Entity<TagFeedback>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<TagFeedback>().Property(x => x.ImageId).HasColumnName(@"ImageId").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<TagFeedback>().Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<TagFeedback>().Property(x => x.OriginalTag).HasColumnName(@"OriginalTag").HasColumnType(@"nvarchar(150)").IsRequired().ValueGeneratedNever().HasMaxLength(150);
            modelBuilder.Entity<TagFeedback>().Property(x => x.Action).HasColumnName(@"Action").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<TagFeedback>().Property(x => x.ReplacementTag).HasColumnName(@"ReplacementTag").HasColumnType(@"nvarchar(150)").ValueGeneratedNever().HasMaxLength(150);
            modelBuilder.Entity<TagFeedback>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime2").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<TagFeedback>().HasKey(@"Id");
        }

        partial void CustomizeTagFeedbackMapping(ModelBuilder modelBuilder);

        #endregion

        #region User Mapping

        private void UserMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().ToTable(@"Users", @"dbo");
            modelBuilder.Entity<User>().Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<User>().Property(x => x.Username).HasColumnName(@"Username").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<User>().Property(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType(@"nvarchar(max)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<User>().Property(x => x.Role).HasColumnName(@"Role").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<User>().Property(x => x.CreatedAt).HasColumnName(@"CreatedAt").HasColumnType(@"datetime2").IsRequired().ValueGeneratedOnAdd().HasDefaultValueSql(@"getdate()");
            modelBuilder.Entity<User>().Property(x => x.LastLogin).HasColumnName(@"LastLogin").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<User>().HasKey(@"Id");
            modelBuilder.Entity<User>().HasIndex(@"Username").IsUnique(true);
        }

        partial void CustomizeUserMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Image>().HasOne(x => x.User).WithMany(op => op.Images).OnDelete(DeleteBehavior.SetNull).HasForeignKey(@"ValidatedByUserId").IsRequired(false);
            modelBuilder.Entity<Image>().HasMany(x => x.TagFeedbacks).WithOne(op => op.Image).OnDelete(DeleteBehavior.Cascade).HasForeignKey(@"ImageId").IsRequired(true);

            modelBuilder.Entity<TagFeedback>().HasOne(x => x.Image).WithMany(op => op.TagFeedbacks).OnDelete(DeleteBehavior.Cascade).HasForeignKey(@"ImageId").IsRequired(true);
            modelBuilder.Entity<TagFeedback>().HasOne(x => x.User).WithMany(op => op.TagFeedbacks).OnDelete(DeleteBehavior.Cascade).HasForeignKey(@"UserId").IsRequired(true);

            modelBuilder.Entity<User>().HasMany(x => x.Images).WithOne(op => op.User).OnDelete(DeleteBehavior.SetNull).HasForeignKey(@"ValidatedByUserId").IsRequired(false);
            modelBuilder.Entity<User>().HasMany(x => x.TagFeedbacks).WithOne(op => op.User).OnDelete(DeleteBehavior.Cascade).HasForeignKey(@"UserId").IsRequired(true);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
