//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 04. 25. 12:54:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ImageInsight.Models
{
    public partial class Image {

        public Image()
        {
            this.ValidationMode = @"manual";
            this.Status = @"pending";
            this.IsValidated = false;
            this.TagFeedbacks = new List<TagFeedback>();
            OnCreated();
        }

        public int Id { get; set; }

        public string ImageUrl { get; set; }

        public string FileName { get; set; }

        public string SourceUrl { get; set; }

        public string SourceType { get; set; }

        public string FlorenceCaption { get; set; }

        public string RamTagsJson { get; set; }

        public string LlmTagsJson { get; set; }

        public string FinalTagsJson { get; set; }

        public string ValidationMode { get; set; }

        public string Status { get; set; }

        public bool IsValidated { get; set; }

        public DateTime? ValidationDate { get; set; }

        public int? ValidatedByUserId { get; set; }

        public DateTime CreatedAt { get; set; }


        public virtual User User { get; set; }


        public virtual IList<TagFeedback> TagFeedbacks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
