//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2026. 04. 25. 12:54:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ImageInsight.Models
{
    public partial class TagFeedback {

        public TagFeedback()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public int ImageId { get; set; }

        public int UserId { get; set; }

        public string OriginalTag { get; set; }

        public string Action { get; set; }

        public string ReplacementTag { get; set; }

        public DateTime CreatedAt { get; set; }


        public virtual Image Image { get; set; }


        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
